### PR TITLE
hotfix: flush offline queue on connect

### PR DESCRIPTION
**Pull request by razvanz**

### CODE REVIEW

**Comment by nicklasmoeller** [comment]
@razvanz what's the intention with this? commit 4386ede (or similar, that actually clears the offline queue) should always be included on services that depend on thrift, otherwise we're going to experience nasty problems

**Comment by razvanz** [comment]
These are Henrik's changes on top of a newer version of thrift.

**Comment by Damgaard** [comment]
@razvanz Is this hot fix still needed?

**Comment by razvanz** [comment]
I guess not since it wasn't needed in the last 2.5 years.

**Pull request closed without merging**
